name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List files in target directory
      run: ls -l target

    - name: Extract JAR version
      id: extract_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set up GitHub CLI
      uses: cli/gh-action@v2
      with:
        version: latest

    - name: Create Release using gh CLI
      run: |
        gh release create "v${{ github.run_number }}" target/TaskApp-${{ env.VERSION }}.jar --title "Release v${{ github.run_number }}" --notes "Automatically created release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
